# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IitjAutoproxy < Formula
  desc "A CLI tool to automatically login to IIT Jodhpur's network firewall."
  homepage "https://github.com/SaahilNotSahil/iitj-autoproxy"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/SaahilNotSahil/iitj-autoproxy/releases/download/0.1.2/iitj-autoproxy_0.1.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "225dcfd69c7f26f23b86614f26c919263b11fb1a642f2bc156fdc25209f91f39"

      def install
        bin.install "bin/autoproxyd"
        bin.install "bin/autoproxy"

        (etc/"iitj-autoproxy").install "autoproxy.config"

        bin.install "scripts/darwin/daemon-start.sh" => "autoproxyd-start"
        bin.install "scripts/darwin/daemon-stop.sh" => "autoproxyd-stop"
        bin.install "scripts/darwin/login.sh" => "autoproxylogin"
      end
    end
    on_arm do
      url "https://github.com/SaahilNotSahil/iitj-autoproxy/releases/download/0.1.2/iitj-autoproxy_0.1.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6d23da27a8b08f1615c7d08c7c245de000691bd0a3e5909a2e31ec0a3584e361"

      def install
        bin.install "bin/autoproxyd"
        bin.install "bin/autoproxy"

        (etc/"iitj-autoproxy").install "autoproxy.config"

        bin.install "scripts/darwin/daemon-start.sh" => "autoproxyd-start"
        bin.install "scripts/darwin/daemon-stop.sh" => "autoproxyd-stop"
        bin.install "scripts/darwin/login.sh" => "autoproxylogin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SaahilNotSahil/iitj-autoproxy/releases/download/0.1.2/iitj-autoproxy_0.1.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "5d2effacd4212cbaec977d014a243d3666a6716bb451856f740a3a8eabe53bf0"

        def install
          bin.install "bin/autoproxyd"
          bin.install "bin/autoproxy"

          (etc/"iitj-autoproxy").install "autoproxy.config"

          bin.install "scripts/darwin/daemon-start.sh" => "autoproxyd-start"
          bin.install "scripts/darwin/daemon-stop.sh" => "autoproxyd-stop"
          bin.install "scripts/darwin/login.sh" => "autoproxylogin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SaahilNotSahil/iitj-autoproxy/releases/download/0.1.2/iitj-autoproxy_0.1.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "373633687990e24aea994eac2eb91e8e73035e15913bb3cdc8c5f2140245f5f0"

        def install
          bin.install "bin/autoproxyd"
          bin.install "bin/autoproxy"

          (etc/"iitj-autoproxy").install "autoproxy.config"

          bin.install "scripts/darwin/daemon-start.sh" => "autoproxyd-start"
          bin.install "scripts/darwin/daemon-stop.sh" => "autoproxyd-stop"
          bin.install "scripts/darwin/login.sh" => "autoproxylogin"
        end
      end
    end
  end

  service do
    run [opt_bin/"autoproxyd"]
    keep_alive true
  end
end
