# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IitjAutoproxy < Formula
  desc "A CLI tool to automatically login to IIT Jodhpur's network firewall."
  homepage "https://github.com/XanderWatson/iitj-autoproxy"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/XanderWatson/iitj-autoproxy/releases/download/v0.1.2/iitj-autoproxy_0.1.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "842a1b3da3fc1426c3fcf6614be6a4ffd145a3e6c3f06e741a6eea85a7717cf2"

      def install
        bin.install "autoproxy"
        bin.install "autoproxyd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/XanderWatson/iitj-autoproxy/releases/download/v0.1.2/iitj-autoproxy_0.1.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "64276192f162b10c75cb957fb95bca45ce5b906ada04875454c72bfab31b39c7"

      def install
        bin.install "autoproxy"
        bin.install "autoproxyd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/XanderWatson/iitj-autoproxy/releases/download/v0.1.2/iitj-autoproxy_0.1.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3dff8e486381a3eed2bbf213671231e6425d769f10abef7af52dee406c723773"

      def install
        bin.install "autoproxy"
        bin.install "autoproxyd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/XanderWatson/iitj-autoproxy/releases/download/v0.1.2/iitj-autoproxy_0.1.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f448d9732a1e308140635cd584e4a796136f181bd367bc9f25ea6a1674426744"

      def install
        bin.install "autoproxy"
        bin.install "autoproxyd"
      end
    end
  end

  def post_install
    etc.install "autoproxy.config"
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
